### ISSUE TITLE
Failed to install "ballr"

### ISSUE THREAD

**Issue by EkremBayar** [rtelmore/ballr#12]
Is package available to use? :)

![image](https://user-images.githubusercontent.com/35973642/86436486-04bce680-bd0b-11ea-8df9-fc04411a715a.png)

**Comment by rtelmore** [comment]
Hi Ekrem,
The package was removed from CRAN for violating their build protocols. It's tough to keep up with the regular changes to basketball-reference.com and remain in compliance with CRAN. You can always install from github using either {remotes} or {devtools} though. Thanks,
Ryan
