### ISSUE TITLE
Use Travis ci and code coverage?

### ISSUE THREAD

**Issue by dewittpe** [rtelmore/ballr#5]
@rtelmore, would you be interested in setting up travis-cil.org and codecov.io for this package?  I have configuration files that could be added to this package easily to get things started.

**Comment by rtelmore** [comment]
I guess I should probably go down those routes. Thanks!

**Comment by rtelmore** [comment]
@dewittpe I'm not sure what I'm supposed to do with travis and codecov. The build fails on travis when I push. Thoughts?

**Comment by dewittpe** [comment]
There is an error in one of the examples.   At the very end of the log file

```
> players %>%
+   dplyr::filter(Pos %in% c("SF")) %>%
+   dplyr::select(Player, link) %>%
+   dplyr::distinct()
Error in filter_impl(.data, quo) : 
  Evaluation error: object 'Pos' not found.
Calls: %>% ... as.data.frame -> filter -> filter.tbl_df -> filter_impl -> .Call
```

I'll dig into the exact location of the bad example soon.

**Comment by rtelmore** [comment]
Ah, got it. I'll fix it.
